spring:
  application:
    name: be
  datasource:
    url: "jdbc:mysql://10.10.11.149:3306/etl_validate_tool_spark"
    username: root
    password: oracle_4U

server:
  port: 8080
  servlet:
    context-path: /